# Generated by Django 5.2.8 on 2025-11-06 14:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='租赁开始日期', verbose_name='租赁开始日期')),
                ('end_date', models.DateField(help_text='租赁结束日期', verbose_name='租赁结束日期')),
                ('actual_return_date', models.DateField(blank=True, help_text='实际还车日期', null=True, verbose_name='实际还车日期')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='租赁总费用', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='总金额')),
                ('status', models.CharField(choices=[('PENDING', '预订中'), ('ONGOING', '进行中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', help_text='当前订单状态', max_length=20, verbose_name='订单状态')),
                ('notes', models.TextField(blank=True, help_text='订单备注信息', null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='customers.customer', verbose_name='客户')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='vehicles.vehicle', verbose_name='车辆')),
            ],
            options={
                'verbose_name': '租赁订单',
                'verbose_name_plural': '租赁订单',
                'db_table': 'rentals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['start_date'], name='rentals_start_d_f5f3b7_idx'), models.Index(fields=['end_date'], name='rentals_end_dat_76d2e2_idx'), models.Index(fields=['status'], name='rentals_status_443aaf_idx'), models.Index(fields=['customer', 'status'], name='rentals_custome_d75db3_idx'), models.Index(fields=['vehicle', 'status'], name='rentals_vehicle_06e21d_idx')],
            },
        ),
    ]
