# Generated by Django 5.2.8 on 2025-12-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_add_return_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='card_returned',
            field=models.BooleanField(default=False, help_text='学生卡是否已归还', verbose_name='学生卡已归还'),
        ),
        migrations.AddField(
            model_name='rental',
            name='card_verified',
            field=models.BooleanField(default=False, help_text='学生卡是否已线下核验', verbose_name='学生卡已核验'),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_method',
            field=models.CharField(choices=[('CASH', '现金押金'), ('STUDENT_CARD', '学生卡抵押'), ('VIP_FREE', 'VIP免押金'), ('FIRST_FREE', '首次租车免押金')], default='CASH', help_text='押金缴纳方式', max_length=20, verbose_name='押金方式'),
        ),
        migrations.AddField(
            model_name='rental',
            name='student_card_image',
            field=models.ImageField(blank=True, help_text='学生卡正面照片', null=True, upload_to='student_cards/%Y/%m/', verbose_name='学生卡照片'),
        ),
        migrations.AddField(
            model_name='rental',
            name='student_id',
            field=models.CharField(blank=True, help_text='学生学号', max_length=50, null=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='rental',
            name='student_major',
            field=models.CharField(blank=True, help_text='院系专业（选填）', max_length=200, null=True, verbose_name='院系专业'),
        ),
        migrations.AddField(
            model_name='rental',
            name='student_name',
            field=models.CharField(blank=True, help_text='学生姓名', max_length=100, null=True, verbose_name='学生姓名'),
        ),
        migrations.AddField(
            model_name='rental',
            name='student_school',
            field=models.CharField(blank=True, help_text='所属学校', max_length=200, null=True, verbose_name='学校名称'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('PENDING', '预订中'), ('ONGOING', '进行中'), ('OVERDUE', '已超时未归还'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], default='PENDING', help_text='当前订单状态', max_length=20, verbose_name='订单状态'),
        ),
    ]
