# Generated by Django 5.2.8 on 2025-11-06 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='客户姓名', max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(help_text='11位手机号码', max_length=20, validators=[django.core.validators.RegexValidator(message='请输入有效的手机号码', regex='^1[3-9]\\d{9}$')], verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, help_text='电子邮箱地址', max_length=254, null=True, verbose_name='邮箱')),
                ('id_card', models.CharField(help_text='18位身份证号码', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='请输入有效的身份证号码', regex='^[1-9]\\d{5}(18|19|20)\\d{2}((0[1-9])|(1[0-2]))(([0-2][1-9])|10|20|30|31)\\d{3}[0-9Xx]$')], verbose_name='身份证号')),
                ('license_number', models.CharField(help_text='驾驶证号码', max_length=20, unique=True, verbose_name='驾照号')),
                ('license_type', models.CharField(choices=[('A', 'A类驾照'), ('B', 'B类驾照'), ('C', 'C类驾照')], default='C', help_text='驾驶证类型', max_length=10, verbose_name='驾照类型')),
                ('member_level', models.CharField(choices=[('NORMAL', '普通会员'), ('VIP', 'VIP会员')], default='NORMAL', help_text='客户会员等级', max_length=20, verbose_name='会员等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id_card'], name='customers_id_card_3d79ab_idx'), models.Index(fields=['license_number'], name='customers_license_02179b_idx'), models.Index(fields=['phone'], name='customers_phone_91048b_idx'), models.Index(fields=['member_level'], name='customers_member__8fd8ac_idx')],
            },
        ),
    ]
