# Generated by Django 5.2.8 on 2025-11-06 14:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='车辆唯一标识', max_length=20, unique=True, verbose_name='车牌号')),
                ('brand', models.CharField(help_text='汽车品牌', max_length=50, verbose_name='品牌')),
                ('model', models.CharField(help_text='汽车型号', max_length=50, verbose_name='型号')),
                ('vehicle_type', models.CharField(help_text='如：轿车、SUV、MPV等', max_length=20, verbose_name='车辆类型')),
                ('color', models.CharField(help_text='车身颜色', max_length=20, verbose_name='颜色')),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='每日租金价格', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='日租金')),
                ('status', models.CharField(choices=[('AVAILABLE', '可用'), ('RENTED', '已租'), ('MAINTENANCE', '维修中')], default='AVAILABLE', help_text='当前车辆状态', max_length=20, verbose_name='车辆状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['license_plate'], name='vehicles_license_b08e3c_idx'), models.Index(fields=['status'], name='vehicles_status_e44f2b_idx'), models.Index(fields=['brand', 'model'], name='vehicles_brand_eef742_idx')],
            },
        ),
    ]
